"""empty message

Revision ID: 6634b15148b4
Revises: 
Create Date: 2018-12-13 14:25:38.219846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6634b15148b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('national_id', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrolment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=200), nullable=True),
    sa.Column('student_name', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['course_name'], ['course.name'], ),
    sa.ForeignKeyConstraint(['student_name'], ['student.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrolment')
    op.drop_table('student')
    op.drop_table('course')
    # ### end Alembic commands ###
